### ISSUE TITLE
pymodbus 3.8.0 compatibility 

### ISSUE THREAD

**Issue by flushto** [alpet83/Solar-Station#1]
##Got the error messages
```
1) Traceback (most recent call last):
  File "~/Solar-Station/sbin/pv1800_ctrl.py", line 9, in <module>
    from pymodbus.framer import ModbusRtuFramer
ImportError: cannot import name 'ModbusRtuFramer' from 'pymodbus.framer' (~/Solar-Station/sbin/venv/lib/python3.9/site-packages/pymodbus/framer/__init__.py)
2) Traceback (most recent call last):
  File "~/Solar-Station/sbin/pv1800_ctrl.py", line 320, in <module>
    if not using_pymodbus():
  File "~/Solar-Station/sbin/pv1800_ctrl.py", line 285, in using_pymodbus
    registers = read_regs(ADDR, 1)
  File "~/Solar-Station/sbin/pv1800_ctrl.py", line 43, in read_regs
    rr = client.read_holding_registers(addr, count, slave=SLAVE_ID)
TypeError: read_holding_registers() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given
```
##Fix:
```
diff --git a/sbin/pv1800_ctrl.py b/sbin/pv1800_ctrl.py
index d420c59..25702b5 100644
--- a/sbin/pv1800_ctrl.py
+++ b/sbin/pv1800_ctrl.py
@@ -6,7 +6,7 @@ import json
 import os
 import minimalmodbus
 from pymodbus.client import ModbusSerialClient as ModbusClient
-from pymodbus.framer import ModbusRtuFramer
+from pymodbus.framer import FramerRTU
 from datetime import datetime
 import logging
 FORMAT = ('%(asctime)-15s %(threadName)-15s '
@@ -40,7 +40,7 @@ def read_regs(addr, count):
     if client:
         for attempt in range(5):
             log.setLevel(logging.ERROR)  # prevent spam about noise bytes from parallel client request
-            rr = client.read_holding_registers(addr, count, slave=SLAVE_ID)
+            rr = client.read_holding_registers(addr, count=count, slave=SLAVE_ID)
             log.setLevel(logging.NOTSET)
             if rr.isError():
                 log.warning(f" ({attempt}) read_holding_registers failed {count}@{addr}")
```

**Comment by alpet83** [comment]
Hi @flushto! Fix added as option in latest commit.
